export const configurationConstants = {
  CONFIG_LANGUAGE: 'CONFIG_LANGUAGE',
  CONFIG_SHAPE: 'CONFIG_SHAPE',
  CONFIG_WIDTH: 'CONFIG_WIDTH',
  CONFIG_HEIGHT: 'CONFIG_HEIGHT',
  CONFIG_RADIUS: 'CONFIG_RADIUS',
  CONFIG_STARTPOS: 'CONFIG_STARTPOS'
}

export const navigationConstants = {
  NAVIGATE_INPROGRESS: 'NAVIGATE_INPROGRESS',
  NAVIGATE_FULFILLED: 'NAVIGATE_FULFILLED',
  NAVIGATE_ERROR: 'NAVIGATE_ERROR',
  SET_XPOS: 'SET_XPOS',
  SET_YPOS: 'SET_YPOS'
}
